HogsApplicationBundle:
    resource: "@HogsApplicationBundle/Resources/config/routing.yml"
    prefix:   /

openiduser_identities:
    resource: "@WGOpenIdUserBundle/Resources/config/routing/identity.yml"
    prefix:   /openid

openiduser_users:
    resource: "@WGOpenIdUserBundle/Resources/config/routing/user.yml"
    prefix:   /people

openiduser_admin:
    resource: "@WGOpenIdUserBundle/Resources/config/routing/admin.yml"
    prefix:   /admin