security:
    providers:
        wg_user_manager:
            id: wg.openid.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            anonymous:  true
            logout:
                path:                       /openid/logout
            fp_openid:
                login_path:                 /openid/login
                check_path:                 /openid/login_check
                create_user_if_not_exists:  true
                provider:                   wg_user_manager
                required_attributes:        [ contact/email, namePerson, namePerson/first, namePerson/last ]

    access_control:
        - { path: ^/secured_area, role: ROLE_USER }
        - { path: ^/openid$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN